version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'java-postgres'
    env_file:
      - .env
    networks:
      - mynetwork
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: ./
    container_name: 'java_app'
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8081:8081"
    restart: on-failure
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db-data:
